Document: rkflashtool
Title: Debian rkflashtool Manual
Author: <insert document author here>
Abstract: This manual describes what rkflashtool is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rkflashtool/rkflashtool.sgml.gz

Format: postscript
Files: /usr/share/doc/rkflashtool/rkflashtool.ps.gz

Format: text
Files: /usr/share/doc/rkflashtool/rkflashtool.text.gz

Format: HTML
Index: /usr/share/doc/rkflashtool/html/index.html
Files: /usr/share/doc/rkflashtool/html/*.html
